---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-cephfs-pvc
  labels:
    appname: busybox-cephfs
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ocs-storagecluster-cephfs
  resources:
    requests:
      storage: 5Gi
