---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc1
  labels:
    appname: busybox1
    placement: busybox1-placement-1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ocs-external-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 5Gi
